services:
  - type: web
    name: ᴊꜰx ᴍᴅ-xᴠ3
    env: node
    plan: free
    repo: https://github.com/Jeffreyfx1/jfx-md-x-v3.git
    branch: main
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: SESSION_ID
        sync: false
      - key: OWNER_NUMBER
        sync: false
